#!/usr/bin/python3

import sys
import os
import os.path
import subprocess
import time
#import getpass
import boto3
from boto3 import Session
import botocore
import traceback

from os.path import expanduser
PATH_TO_CREDENTIALS_DIR = expanduser("~") + "/.6172_cloud"
PATH_TO_CREDENTIALS = PATH_TO_CREDENTIALS_DIR+"/p4_cloud_credentials.pobj"
def get_credentials():
  credentials = eval(open(PATH_TO_CREDENTIALS).read())
  return credentials
global_credentials = get_credentials()
def getuser():
  return global_credentials["USERNAME"]
def get_aws_id():
  return global_credentials["ID"]
def get_aws_secret():
  return global_credentials["SECRET"]

# Amazon S3 bucket name.
student_bucket = "6172-test-filesystem"

# Key prefix for user folders in bucket.
object_key_prefix = "userhome"

# Key folder for game lists to be tested.
object_key_tests = "autotest_test_uploads"

# Server for submitting autotests.
submit_server = "cloud9.csail.mit.edu:4040"


# Define ANSI escape sequences.
class ansi_esc:
  RESET     = '\033[0m'
  BOLD      = '\033[1m'
  UNDERLINE = '\033[4m'
  RED       = '\033[31m'
  GREEN     = '\033[32m'
  YELLOW    = '\033[33m'
  BLUE      = '\033[34m'
  MAGENTA   = '\033[35m'
  CYAN      = '\033[36m'


# Define wrappers for ANSI escape sequences.
def term_bold(s):
  return ansi_esc.BOLD      + s + ansi_esc.RESET
def term_underline(s):
  return ansi_esc.UNDERLINE + s + ansi_esc.RESET
def term_red(s):
  return ansi_esc.RED       + s + ansi_esc.RESET
def term_green(s):
  return ansi_esc.GREEN     + s + ansi_esc.RESET
def term_yellow(s):
  return ansi_esc.YELLOW    + s + ansi_esc.RESET
def term_blue(s):
  return ansi_esc.BLUE      + s + ansi_esc.RESET
def term_magenta(s):
  return ansi_esc.MAGENTA   + s + ansi_esc.RESET
def term_cyan(s):
  return ansi_esc.CYAN      + s + ansi_esc.RESET


if __name__ == "__main__":
  # Give basic calling convention if requested.
  if len(sys.argv) != 2 or sys.argv[1] == "-h" or sys.argv[1] == "--help":
    sys.stderr.write("Usage: {0} GAME_LIST_PATH\n".format(os.path.basename(__file__)))
    exit(1)

  session = Session(aws_access_key_id = get_aws_id(), aws_secret_access_key = get_aws_secret(), region_name="us-east-1")
  # Read the argument.
  game_list_path = sys.argv[1]

  # Check for path existence.
  try:
    if not os.path.exists(game_list_path):
      exit(term_red(
        "[ERROR] Path '{}' does not exist.".format(game_list_path)
      ))
    if not os.path.isfile(game_list_path):
      exit(term_red(
        "[ERROR] Path '{}' is not a file.".format(game_list_path)
      ))
  except OSError:
    traceback.print_exc(1)
    exit(term_red(
      "[ERROR] Cannot test path '{}' for existence.".format(game_list_path)
    ))

  # Get the game list's basename.
  try:
    game_list_basename = os.path.basename(game_list_path)
  except OSError:
    traceback.print_exc(1)
    exit(term_red(
      "[ERROR] Cannot get basename for path '{}'.".format(game_list_path)
    ))

  # Fetch the bucket.
  #s3 = boto3.resource('s3')
  s3 = session.resource('s3')
  bucket = s3.Bucket(student_bucket)

  # Test for bucket existence.
  try:
    s3.meta.client.head_bucket(Bucket = student_bucket)
  except botocore.exceptions.ClientError as e:
    error_code = int(e.response["Error"]["Code"])
    if error_code == 404:
      exit(term_red(
        "[ERROR] Amazon S3 Bucket '{}' doesn't exist.".format(student_bucket)
      ))
    else:
      traceback.print_exc(1)
      exit(term_red(
        "[ERROR] Cannot get Amazon S3 bucket."
      ))

  # Generate student's Amazon IAM username (on staff's account).
  try:
    athena_user = str(getuser())
    iam_user = "student-" + athena_user
  except Exception:
    traceback.print_exc(1)
    exit(term_red(
      "[ERROR] Cannot get login name."
    ))

  # Upload the game list to the student bucket.
  s3_client = session.client('s3')
  upload_key = "/".join([
    object_key_prefix,
    iam_user,
    object_key_tests, 
    game_list_basename
  ])
  print("Uploading game list '{}' to '~/s3home/{}/{}' on instance...".format(
    game_list_basename, object_key_tests, game_list_basename))
  try:
    s3_client.upload_file(
      game_list_path, 
      student_bucket,
      upload_key,
      ExtraArgs = {
        "ACL": "bucket-owner-full-control"
      }
    )
  except Exception:
    traceback.print_exc(1)
    exit(term_red(
      "[ERROR] Cannot upload game list to Amazon S3 bucket."
    ))

  # Echo upload completion.
  print(term_green("Upload complete!"))

  # Submit the game list to the server.
  print("Submitting autotest with game list '{}' to the server...".format(game_list_basename))
  try:
    response = subprocess.check_output(
      "wget -q -O - '{}/autotest/{}/{}'".format(
        submit_server,
        game_list_basename.replace("'", "'\"'\"'"), 
        athena_user),
      shell = True, universal_newlines=True)
  except subprocess.CalledProcessError:
    traceback.print_exc(1)
    exit(term_red(
      "[ERROR] Cannot contact submission server '{}'.".format(submit_server)
    ))

  # Check response for autotest ID.
  response = response.strip()
  response_parsed = response.split(':')
  if len(response_parsed) != 2 or response_parsed[0] != 'AUTOTEST_ID':
    exit(term_red(
      "[SERVER ERROR] {}.".format(response)
    ))
  else:
    autotest_id = response_parsed[1]
    print(term_green(
      "Submission success! Autotest ID is {}.".format(autotest_id)
    ))

  # Check status of submission until it has started.
  print("Polling status of autotest...")
  poll_count = 0
  timeout = 2
  while True:
    # Echo the poll count (with no trailing newline)
    poll_count += 1
    print("POLL {}:".format(poll_count), end=' ')

    # Poll the server about the status.
    try:
      response = subprocess.check_output(
        "wget -q -O - '{}/at_status/{}'".format(
          submit_server,
          autotest_id),
        shell = True, universal_newlines=True)
    except subprocess.CalledProcessError:
      print(term_yellow(
        "\rPOLL {}: ".format(poll_count) + \
        "[WARNING] Cannot contact status server '{}'.".format(submit_server)
      ))
      time.sleep(timeout)
      continue
    
    # Parse the response and re-poll on non-fatal error.
    response = response.strip()
    response_parsed = response.split(':', 2)
    if response_parsed[0] != 'Autotest Status':
      if len(response):
        print(term_yellow(
          "\rPOLL {}: ".format(poll_count) + \
          "[SERVER WARNING] {}.".format(response)
        ))
      else:
        print("Re-polling in {} seconds...".format(timeout))
      time.sleep(timeout)
      continue
    
    # Quit on fatal error.
    if response_parsed[1] == "ERROR":
      exit(term_red(
        "\rPOLL {}: ".format(poll_count) + \
        "[SERVER ERROR] {}.".format(response_parsed[2])
      ))

    # Echo URL on success.
    if response_parsed[1] == "STARTED":
      print(term_green(
        "\rPOLL {}: ".format(poll_count) + \
        "Autotest started! View it running at " + \
        "http://scrimmage.csail.mit.edu/autotest?autoid={}".format(autotest_id)
        #  "cloud9.csail.mit.edu/autotest?autoid={}".format(autotest_id)
      ))
      break
